#### numpy task

In [3]:
import pandas as pd

data = pd.read_csv("C:\\Users\\VIGNESH\\OneDrive\\Documents\\genai-python\\ml\\employee_data.csv")

In [4]:
data

   EmpID     Name Department  Age  Salary  Experience        City
0    101     Arun         IT   25   35000           2     Chennai
1    102    Priya         HR   29   42000           5     Madurai
2    103    Kumar         IT   32   58000           8     Chennai
3    104    Divya    Finance   27   39000           3  Coimbatore
4    105    Rahul         IT   24   30000           1       Salem
5    106    Meena         HR   35   62000          10     Chennai
6    107  Sathish    Finance   31   51000           7     Madurai
7    108     Nila         IT   28   47000           4  Coimbatore
8    109    Vijay      Sales   30   44000           6     Chennai
9    110    Kavya      Sales   26   36000           2       Salem

In [5]:
df = pd.DataFrame(data)
df

   EmpID     Name Department  Age  Salary  Experience        City
0    101     Arun         IT   25   35000           2     Chennai
1    102    Priya         HR   29   42000           5     Madurai
2    103    Kumar         IT   32   58000           8     Chennai
3    104    Divya    Finance   27   39000           3  Coimbatore
4    105    Rahul         IT   24   30000           1       Salem
5    106    Meena         HR   35   62000          10     Chennai
6    107  Sathish    Finance   31   51000           7     Madurai
7    108     Nila         IT   28   47000           4  Coimbatore
8    109    Vijay      Sales   30   44000           6     Chennai
9    110    Kavya      Sales   26   36000           2       Salem

In [6]:
#1
print(df.head())
print(df.tail(3))
print(df.shape)
print(df.dtypes)

   EmpID   Name Department  Age  Salary  Experience        City
0    101   Arun         IT   25   35000           2     Chennai
1    102  Priya         HR   29   42000           5     Madurai
2    103  Kumar         IT   32   58000           8     Chennai
3    104  Divya    Finance   27   39000           3  Coimbatore
4    105  Rahul         IT   24   30000           1       Salem
   EmpID   Name Department  Age  Salary  Experience        City
7    108   Nila         IT   28   47000           4  Coimbatore
8    109  Vijay      Sales   30   44000           6     Chennai
9    110  Kavya      Sales   26   36000           2       Salem
(10, 7)
EmpID         int64
Name            str
Department      str
Age           int64
Salary        int64
Experience    int64
City            str
dtype: object

In [8]:
#2
result = df[(df["Department"] == "IT") & (df["Salary"] > 40000)]
result

   EmpID   Name Department  Age  Salary  Experience        City
2    103  Kumar         IT   32   58000           8     Chennai
7    108   Nila         IT   28   47000           4  Coimbatore

In [10]:
#3
result = df.sort_values(by = "Salary",ascending=False)
print(result[["Name","Department","Salary"]])

      Name Department  Salary
5    Meena         HR   62000
2    Kumar         IT   58000
6  Sathish    Finance   51000
7     Nila         IT   47000
8    Vijay      Sales   44000
1    Priya         HR   42000
3    Divya    Finance   39000
9    Kavya      Sales   36000
0     Arun         IT   35000
4    Rahul         IT   30000

In [16]:
#4
print("means Salary : ",df["Salary"].mean())
print("max Salary : ",df["Salary"].max())
print("min Salary : ",df["Salary"].min())
print("average age : ",df["Age"].mean())

means Salary :  44400.0
max Salary :  62000
min Salary :  30000
average age :  28.7

In [26]:
#5
result = df.groupby("Department").agg(
    EmployeeCount=("EmpID", "count"),
    AverageSalary=("Salary", "mean"),
    HighestSalary=("Salary", "max")
)

result = result.sort_values(
    by="AverageSalary",
    ascending=False
)

print(result)

            EmployeeCount  AverageSalary  HighestSalary
Department
HR                      2        52000.0          62000
Finance                 2        45000.0          51000
IT                      4        42500.0          58000
Sales                   2        40000.0          44000

In [33]:
#6
df["Annualsalary"] = df["Salary"] *12
print(df[["Name","Salary","Annualsalary"]])

      Name  Salary  Annualsalary
0     Arun   35000        420000
1    Priya   42000        504000
2    Kumar   58000        696000
3    Divya   39000        468000
4    Rahul   30000        360000
5    Meena   62000        744000
6  Sathish   51000        612000
7     Nila   47000        564000
8    Vijay   44000        528000
9    Kavya   36000        432000

In [34]:
#7
df_copy = df.copy()


df_copy.loc[0, "City"] = None


df_copy = pd.concat(
    [df_copy, df_copy.iloc[[1]]],
    ignore_index=True
)

print("Missing values:")
print(df_copy.isnull().sum())


df_copy["City"] = df_copy["City"].fillna("Unknown")


df_copy = df_copy.drop_duplicates().reset_index(drop=True)

print("\nCleaned DataFrame:")
print(df_copy)

print("\nRemaining duplicates:", df_copy.duplicated().sum())

Missing values:
EmpID           0
Name            0
Department      0
Age             0
Salary          0
Experience      0
City            1
Annualsalary    0
dtype: int64

Cleaned DataFrame:
   EmpID     Name Department  Age  Salary  Experience        City  \
0    101     Arun         IT   25   35000           2     Unknown
1    102    Priya         HR   29   42000           5     Madurai
2    103    Kumar         IT   32   58000           8     Chennai
3    104    Divya    Finance   27   39000           3  Coimbatore
4    105    Rahul         IT   24   30000           1       Salem
5    106    Meena         HR   35   62000          10     Chennai
6    107  Sathish    Finance   31   51000           7     Madurai
7    108     Nila         IT   28   47000           4  Coimbatore
8    109    Vijay      Sales   30   44000           6     Chennai
9    110    Kavya      Sales   26   36000           2       Salem

   Annualsalary
0        420000
1        504000
2        696000
3        468000
4        360000
5        744000
6        612000
7        564000
8        528000
9        432000

Remaining duplicates: 0

In [35]:
#8
conditions = [
    df["Salary"] >= 50000,
    (df["Salary"] >= 40000) & (df["Salary"] < 50000),
    df["Salary"] < 40000
]

choices = ["High", "Medium", "Low"]

df["SalaryLevel"] = pd.Series(
    pd.NA, index=df.index, dtype="string"
)

import numpy as np

df["SalaryLevel"] = np.select(
    conditions,
    choices,
    default="Low"
)

print(df[["Name", "Salary", "SalaryLevel"]])

      Name  Salary SalaryLevel
0     Arun   35000         Low
1    Priya   42000      Medium
2    Kumar   58000        High
3    Divya   39000         Low
4    Rahul   30000         Low
5    Meena   62000        High
6  Sathish   51000        High
7     Nila   47000      Medium
8    Vijay   44000      Medium
9    Kavya   36000         Low

In [36]:
#9
marks = pd.DataFrame({
    "EmpID": [101, 103, 105, 108, 110],
    "TrainingScore": [85, 92, 78, 88, 90]
})

result = pd.merge(
    df,
    marks,
    on="EmpID",
    how="left"
)

print(result[["EmpID", "Name", "TrainingScore"]])

   EmpID     Name  TrainingScore
0    101     Arun           85.0
1    102    Priya            NaN
2    103    Kumar           92.0
3    104    Divya            NaN
4    105    Rahul           78.0
5    106    Meena            NaN
6    107  Sathish            NaN
7    108     Nila           88.0
8    109    Vijay            NaN
9    110    Kavya           90.0

In [37]:
#10
department_avg = df.groupby("Department")["Salary"].mean()

highest_department = department_avg.idxmax()
highest_average = department_avg.max()

print("Department with highest average salary:", highest_department)
print("Highest department average salary:", highest_average)


overall_average = df["Salary"].mean()

above_average = df[df["Salary"] > overall_average]

print("\nOverall average salary:", overall_average)
print("\nEmployees earning above average:")
print(above_average[["Name", "Department", "Salary"]])

Department with highest average salary: HR
Highest department average salary: 52000.0

Overall average salary: 44400.0

Employees earning above average:
      Name Department  Salary
2    Kumar         IT   58000
5    Meena         HR   62000
6  Sathish    Finance   51000
7     Nila         IT   47000