#### python pandas

In [1]:
import pandas as pd

#### pandas series

In [2]:
carname = pd.Series(["honda","toyota","tata","bmw"])
carname

0     honda
1    toyota
2      tata
3       bmw
dtype: str

In [3]:
carname.loc[1:10]

1    toyota
2      tata
3       bmw
dtype: str

In [4]:
print(carname.size)
print(carname.shape)

4
(4,)

In [5]:
print(carname[1])

toyota

In [6]:
carname.info()

<class 'pandas.Series'>
RangeIndex: 4 entries, 0 to 3
Series name: None
Non-Null Count  Dtype
--------------  -----
4 non-null      str
dtypes: str(1)
memory usage: 164.0 bytes

In [8]:
carcolor=pd.Series(["black","white","grey","green"])

In [9]:
carcolor

0    black
1    white
2     grey
3    green
dtype: str

In [14]:
cardata =pd.DataFrame({
    
    "name":carname,
    "color":carcolor

    
})
cardata

     name  color
0   honda  black
1  toyota  white
2    tata   grey
3     bmw  green

In [15]:
print(cardata.size)
print(cardata.shape)
print(cardata.dtypes)

8
(4, 2)
name     str
color    str
dtype: object

In [16]:
cardata.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      str
 1   color   4 non-null      str
dtypes: str(2)
memory usage: 196.0 bytes

In [17]:
cardata.isna().sum()

name     0
color    0
dtype: int64

In [22]:
import pandas as pd
studetail =({
    
    "stuname" : ["ram","somu","shaw","kay"],
    "stuage" : ["23","24","23","21"]

})
dd = pd.DataFrame(studetail)
dd

  stuname stuage
0     ram     23
1    somu     24
2    shaw     23
3     kay     21

In [26]:
df = pd.read_csv("C:\\Users\\VIGNESH\\OneDrive\\Documents\\genai-python\\ml\\Car_sales.csv")
df

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [27]:
df.to_csv("test.csv",index=False)

In [29]:
new=pd.read_csv("test.csv")
new

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Volvo,V40,3.545,NaN,Passenger,24.40,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.50,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.80,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.50,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.00,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [30]:
print(new.dtypes)

Manufacturer               str
Model                      str
Sales_in_thousands     float64
__year_resale_value    float64
Vehicle_type               str
Price_in_thousands     float64
Engine_size            float64
Horsepower             float64
Wheelbase              float64
Width                  float64
Length                 float64
Curb_weight            float64
Fuel_capacity          float64
Fuel_efficiency        float64
Latest_Launch              str
Power_perf_factor      float64
dtype: object

In [31]:
new.info()

<class 'pandas.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Manufacturer         157 non-null    str
 1   Model                157 non-null    str
 2   Sales_in_thousands   157 non-null    float64
 3   __year_resale_value  121 non-null    float64
 4   Vehicle_type         157 non-null    str
 5   Price_in_thousands   155 non-null    float64
 6   Engine_size          156 non-null    float64
 7   Horsepower           156 non-null    float64
 8   Wheelbase            156 non-null    float64
 9   Width                156 non-null    float64
 10  Length               156 non-null    float64
 11  Curb_weight          155 non-null    float64
 12  Fuel_capacity        156 non-null    float64
 13  Fuel_efficiency      154 non-null    float64
 14  Latest_Launch        157 non-null    str
 15  Power_perf_factor    155 non-null    float64
dtypes: float64(12), str(4)
memory usage: 19.8 KB

In [32]:
new.isna().sum()

Manufacturer            0
Model                   0
Sales_in_thousands      0
__year_resale_value    36
Vehicle_type            0
Price_in_thousands      2
Engine_size             1
Horsepower              1
Wheelbase               1
Width                   1
Length                  1
Curb_weight             2
Fuel_capacity           1
Fuel_efficiency         3
Latest_Launch           0
Power_perf_factor       2
dtype: int64

In [33]:
new.describe()

,Sales_in_thousands,__year_resale_value,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Power_perf_factor
count,157.000000,121.000000,155.000000,156.000000,156.000000,156.000000,156.000000,156.000000,155.000000,156.000000,154.000000,155.000000
mean,52.998076,18.072975,27.390755,3.060897,185.948718,107.487179,71.150000,187.343590,3.378026,17.951923,23.844156,77.043591
std,68.029422,11.453384,14.351653,1.044653,56.700321,7.641303,3.451872,13.431754,0.630502,3.887921,4.282706,25.142664
min,0.110000,5.160000,9.235000,1.000000,55.000000,92.600000,62.600000,149.400000,1.895000,10.300000,15.000000,23.276272
25%,14.114000,11.260000,18.017500,2.300000,149.500000,103.000000,68.400000,177.575000,2.971000,15.800000,21.000000,60.407707
50%,29.450000,14.180000,22.799000,3.000000,177.500000,107.000000,70.550000,187.900000,3.342000,17.200000,24.000000,72.030917
75%,67.956000,19.875000,31.947500,3.575000,215.000000,112.200000,73.425000,196.125000,3.799500,19.575000,26.000000,89.414878
max,540.561000,67.550000,85.500000,8.000000,450.000000,138.700000,79.900000,224.500000,5.572000,32.000000,45.000000,188.144323

In [34]:
new.head(7)

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639
5,Audi,A6,18.780,23.555,Passenger,33.95,2.8,200.0,108.7,76.1,192.0,3.561,18.5,22.0,8/9/2011,84.565105
6,Audi,A8,1.380,39.000,Passenger,62.00,4.2,310.0,113.0,74.0,198.2,3.902,23.7,21.0,2/27/2012,134.656858

In [35]:
new.tail()

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
152,Volvo,V40,3.545,NaN,Passenger,24.4,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.5,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.8,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.5,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.0,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [36]:
new.loc[0]

Manufacturer               Acura
Model                    Integra
Sales_in_thousands        16.919
__year_resale_value        16.36
Vehicle_type           Passenger
Price_in_thousands          21.5
Engine_size                  1.8
Horsepower                 140.0
Wheelbase                  101.2
Width                       67.3
Length                     172.4
Curb_weight                2.639
Fuel_capacity               13.2
Fuel_efficiency             28.0
Latest_Launch           2/2/2012
Power_perf_factor       58.28015
Name: 0, dtype: object

In [42]:
new["Manufacturer"].value_counts()

Manufacturer
Dodge         11
Ford          11
Chevrolet      9
Mercedes-B     9
Toyota         9
Chrysler       7
Mitsubishi     7
Nissan         7
Lexus          6
Mercury        6
Oldsmobile     6
Pontiac        6
Volkswagen     6
Volvo          6
Cadillac       5
Honda          5
Saturn         5
Acura          4
Buick          4
Plymouth       4
Audi           3
BMW            3
Hyundai        3
Jeep           3
Lincoln        3
Porsche        3
Saab           2
Subaru         2
Infiniti       1
Jaguar         1
Name: count, dtype: int64

In [46]:
new[new["Manufacturer"]=="Volvo"]

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
151,Volvo,S40,16.957,NaN,Passenger,23.4,1.9,160.0,100.5,67.6,176.6,2.998,15.8,25.0,2/18/2011,66.113057
152,Volvo,V40,3.545,NaN,Passenger,24.4,1.9,160.0,100.5,67.6,176.6,3.042,15.8,25.0,9/21/2011,66.498812
153,Volvo,S70,15.245,NaN,Passenger,27.5,2.4,168.0,104.9,69.3,185.9,3.208,17.9,25.0,11/24/2012,70.654495
154,Volvo,V70,17.531,NaN,Passenger,28.8,2.4,168.0,104.9,69.3,186.2,3.259,17.9,25.0,6/25/2011,71.155978
155,Volvo,C70,3.493,NaN,Passenger,45.5,2.3,236.0,104.9,71.5,185.7,3.601,18.5,23.0,4/26/2011,101.623357
156,Volvo,S80,18.969,NaN,Passenger,36.0,2.9,201.0,109.9,72.1,189.8,3.600,21.1,24.0,11/14/2011,85.735655

In [47]:
pd.crosstab(new["Manufacturer"],new["Fuel_capacity"])

Fuel_capacity,10.3,11.9,12.0,12.1,12.5,12.7,13.1,13.2,13.7,14.0,...,22.5,23.2,23.7,24.3,25.0,25.1,25.4,26.0,30.0,32.0
Manufacturer,,,,,,,,,,,,,,,,,,,,,
Acura,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Audi,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
BMW,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Buick,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Cadillac,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Chevrolet,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Chrysler,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Dodge,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,2
Ford,0,0,0,0,0,1,0,1,0,0,...,0,0,0,0,0,1,0,2,0,0
Honda,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Hyundai,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Infiniti,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Jaguar,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Jeep,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Lexus,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,1,0,0,0
Lincoln,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
Mercedes-B,0,0,0,0,0,0,0,0,0,1,...,0,2,0,0,0,0,0,0,0,0
Mercury,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Mitsubishi,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
Nissan,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
Oldsmobile,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
Plymouth,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Pontiac,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
Porsche,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Saab,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Saturn,0,0,0,3,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Subaru,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Toyota,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
Volkswagen,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
Volvo,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0